### ISSUE TITLE
Landing Page : 1st Try Now for Free not working

### ISSUE THREAD

**Issue by ptrisnodjojo00** [mercury-squad/billy-frontend#36]
Browser: Safari & Chrome

Page: Landing Page https://invoicebilly.netlify.app/welcome

Steps to reproduce: Click Try Now For Free, linked to sign up page

Expected result:
Open Create account page and user can sign up

Actual result:
Try Now for Free button not working
<img width="1440" alt="Screen Shot 2022-07-09 at 1 07 20 PM" src="https://user-images.githubusercontent.com/100663792/178121120-80f575c0-2a02-4dcb-bdba-d1c6067b459a.png">

**Comment by gabrielgimenes92** [comment]
Issue duplicated, see issue #22.
