### ISSUE TITLE
Create New Invoice : Add new project, Select due date, add new client

### ISSUE THREAD

**Issue by ptrisnodjojo00** [mercury-squad/billy-frontend#43]
Browser: Safari & Chrome

Page: New Invoices page https://invoicebilly.netlify.app/invoices/new

Steps to reproduce: add new input field in text form

Actual result:
User can't choose to add new project
USer can't choose to add new client
User can't choose due date

Expected result:
- user can add new project 
- label for due date, open calendar and user can choose due date
- user can add new client if the client is not in the client list
<img width="1436" alt="Screen Shot 2022-07-09 at 1 38 09 PM" src="https://user-images.githubusercontent.com/100663792/178122264-b6799f13-5e25-4981-bc6a-1ccbad32752e.png">

<img width="1440" alt="Screen Shot 2022-07-09 at 1 40 07 PM" src="https://user-images.githubusercontent.com/100663792/178122291-7099e1c9-fbc6-4831-b3eb-c1061b939491.png">

**Comment by KariGarcia** [comment]
Addressed label in Due date. As for the new client creation, we wont be able to support this feature
