### ISSUE TITLE
Mobile : Landing Page - missing menu

### ISSUE THREAD

**Issue by ptrisnodjojo00** [mercury-squad/billy-frontend#49]
Mobile version : IOS
Page: landing page https://invoicebilly.netlify.app/welcome

Steps to reproduce : Add hamburger menu, when click open navigation menu & login button

Actual result:
No hamburger menu

Expected result:
Hamburger menu to access navigation & login button
![IMG_2121](https://user-images.githubusercontent.com/100663792/178136292-73bc39e5-2148-4404-8ca6-3790ec38cbf1.PNG)

**Comment by gabrielgimenes92** [comment]
Issue duplicated, see issue #23.

**Comment by gabrielgimenes92** [comment]
Issue duplicated, see issue #23.
