### ISSUE TITLE
Landing Page : Nav menu scroll to the correspondent content

### ISSUE THREAD

**Issue by ptrisnodjojo00** [mercury-squad/billy-frontend#54]
Browser: Safari & Chrome

Page: https://invoicebilly.netlify.app/welcome

Steps to reproduce:
- click Feature, scroll to <section class= "Feature">
- click Our Team, scroll to  <section class= "team">
- click Contact us scroll to  <section class= "contactUs">

Actual result:
-When user click on nav menu, landing page will reload

Expected result:
- When user click on nav menu, it will scroll to the correspondent content

**Comment by gabrielgimenes92** [comment]
Issue duplicated, see issue #26.
